server:
  port: 1111


management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    dev
#    url: jdbc:mysql://localhost:3306/stock_position
#    username: dev
#    password: dev
#    prod
    url: jdbc:mysql://rm-bp1qp12e2g8zgmfe94o.mysql.rds.aliyuncs.com:3306/stock_positon
    username: position
    password: position-dev-299

  jpa:
    hibernate:
#      ????
      ddl-auto: update
#      ?????sql??
    show-sql: true

  thymeleaf:
    cache: false

  mvc:
    static-path-pattern: /static/**




logging:
  level:
    root: INFO
  file:
    #      path: ./logs/${spring.application.name}   # path和name设置一个即可，name的优先级高
    name: ./logs/nohup.log



pm:
  param:
#    dev-15900777503
#    tushareToken: 9897de9903a7ce04fa4b85bab5e531b6033d63e197faa87b7de5317f
#    prod-15300662389
    tushareToken: a17ec1c102ff651f3c74d55e8c4b01493cb84e4198f702627d055470
    isDataInitialized: false


