server:
  port: 1111


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stock_position
#    url: jdbc:mysql://rm-bp1qp12e2g8zgmfe94o.mysql.rds.aliyuncs.com:3306/stock_positon
    type: com.alibaba.druid.pool.DruidDataSource
    username: dev
    password: dev
#    username: position
#    password: position-dev-299
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
#      ????
      ddl-auto: update
#      ?????sql??
    show-sql: true

  thymeleaf:
    cache: false

  mvc:
    static-path-pattern: /static/**