server:
  port: 1111


management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
#      ????
      ddl-auto: update
#      ?????sql??
    show-sql: true

  thymeleaf:
    cache: false

  mvc:
    static-path-pattern: /static/**




logging:
  level:
    root: INFO
  file:
    #      path: ./logs/${spring.application.name}   # path和name设置一个即可，name的优先级高
    name: ./logs/nohup.log



pm:
  param:
#    dev-15900777503
    tushareToken: 9897de9903a7ce04fa4b85bab5e531b6033d63e197faa87b7de5317f
#    prod-15300662389
#    tushareToken: a17ec1c102ff651f3c74d55e8c4b01493cb84e4198f702627d055470
#    prod-15900959511
#    tushareToken: 80290c33bdb09092f1e47bbd72722af5424af264d1d0ad32bf8ebb14

    isDataInitialized: false


